# Create this file as "secrets.toml" in your project root directory
# (same level as your main app.py file)

# Admin password for Foundation system
admin_password = "admin123"

# You can also add different passwords for different systems if needed:
# foundation_admin_password = "foundation_password"
# employee_admin_password = "employee_password" 
# payroll_admin_password = "payroll_password"

# Database connections (if needed)
# [database]
# host = "localhost"
# port = 5432
# username = "admin"
# password = "db_password"

# API keys (if needed)
# api_key = "your_api_key_here"
